export const elements = {
    buttonPlay: document.querySelector(".play"),
    buttonStop: document.querySelector(".stop"),
    buttonIncrease: document.querySelector(".increase"),
    buttonDecrease: document.querySelector(".decrease"),
    buttonSoundFlorest: document.querySelector(".florest"),
    buttonSoundRain: document.querySelector(".rain"),
    buttonSoundCoffeeShop: document.querySelector(".coffee-shop"),
    buttonSoundFireplace: document.querySelector(".fireplace"),
    buttonLightMode: document.querySelector(".light-mode"),
    buttonDarkMode: document.querySelector(".dark-mode"),
    volFlorest: document.querySelector("#volume-florest"),
    volRain: document.querySelector("#volume-rain"),
    volCoffeeShop: document.querySelector("#volume-coffee-shop"),
    volFireplace: document.querySelector("#volume-fireplace"),
    timerMinutes: document.querySelector(".minutes"),
    timerSeconds: document.querySelector(".seconds"),
}
